### ISSUE TITLE
Harmozine dependencies in .cabal file

### ISSUE THREAD

**Issue by jsantos17** [stackbuilders/octohat#27]
If we list a package more than once we should be consistent on the version we request. Even better, we should request every package only once

@sestrella

**Comment by finlay** [comment]
Hi

Regarding dependencies:
Is it possible to keep the versions compatible with the [Stackage LTS 2.1](https://www.stackage.org/snapshot/lts-2.1) release ? 

I made some changes in a pull request to do that #20. Should be a matter of keeping them. 

Finlay

**Comment by jsantos17** [comment]
@finlay that's definitely a concern for me. Using Stackage alleviates a lot of headaches.

**Comment by sestrella** [comment]
@jsantos17 what else we are missing in order to close this issue? there is a [PR](https://github.com/stackbuilders/octohat/pull/28) already merged related to this

**Comment by juanpaucar** [comment]
@jsantos17 It all works with Stackage 2.1, so maybe we can close this issue

**Comment by jsantos17** [comment]
@juanpaucar already tested it with Stackage LTS and it appears to work fine.

**Comment by jsantos17** [comment]
#27 fixed this. Closing.
