### ISSUE TITLE
Pagination design

### ISSUE THREAD

**Issue by finlay** [stackbuilders/octohat#29]
Has anyone thought about the pagination issue ? What is the best design ?

https://developer.github.com/v3/#pagination

I would like the getRequestTo function to be able to keep asking for pages until all the data is sourced. I am going to work on that now. This would hide the pagination API though, if someone wanted to use it.

Advantage is that no other functions need to change.

**Comment by sestrella** [comment]
@finlay  your approach sounds good, just to double check are you planning to keep the pagination info inside a `StateT` monad? right now our current `GitHub` type alias looks like:

```haskell
type GitHub = EitherT GitHubReturnStatus (ReaderT BearerToken IO)
```

Maybe we need to consider switching from a `ReaderT` monad to a `StateT` monad, something like:

```haskell
data Pagination = Pagination ...

type GitHub = EitherT GitHubReturnStatus (StateT (BearerToken, Pagination) IO)
```

Sounds reasonable? Please let me know your thoughts

\cc @jsl @juanpaucar @jsantos17

**Comment by finlay** [comment]
Hi @sestrella 

I like the idea of replacing the ReaderT with StateT. Actually was going to suggest it!

I'll get on and start the implementation. 

The Pagination data will include the "per_page" value, and information from the "Link" tag. Also, thought I would add a setting along the line of a "just get all" to repeatedly call the API to get everything.

F

**Comment by juanpaucar** [comment]
@sestrella @finlay indeed it sounds like a good idea to deal with paginated results

**Comment by jsantos17** [comment]
@sestrella @juanpaucar @finlay @jsl this was done with #31. Any issue with closing this?
